---
author: 'Karl Uibo 153620IVEM'
date: 'May 2018'
institution: 'tallinn university of technology'
division: 'School of Information Technologies'
advisor: 'Supervisor: Olev Märtens'
#altadvisor: 'Your Other Advisor'
# Delete line 7 if you only have one advisor
department: 'Thomas Johann Seebeck Department of Electronics'
degree: 'Professor'
title: 'analysis of flight data for weather dependant multiple execution autonomous missions'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
  thesisdown::thesis_pdf: default
#  thesisdown::thesis_gitbook: default
#  thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
originality: |
  `r if(knitr:::is_latex_output()) paste(readLines("pre/00-originality.Rmd", encoding = "UTF-8"), collapse = '\n  ')`
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("pre/00-abstract.Rmd", encoding = "UTF-8"), collapse = '\n  ')`
annotatsioon: |
  `r if(knitr:::is_latex_output()) paste(readLines("pre/00-annotatsioon.Rmd", encoding = "UTF-8"), collapse = '\n  ')`
abbrvs: |
  `r if(knitr:::is_latex_output()) paste(readLines("pre/00-abbrvs.Rmd", encoding = "UTF-8"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.
bibliography: bib/thesis.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
lot: true
lof: true
always_allow_html: yes
#space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
# Probably should install this from my own repo!!
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
```

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Introduction {.unnumbered}

Currently the autonomy of multirotor aircraft is limited to single flights. A mission can be made that traverses a given path and points its camera at points of interest. The current technology lets the pilot assign the speed of flight during the traversal of the mission. Eli Ltd has developed a technology that they call _nests_. With this technology the batteries of a multirotor can be recharged and swapped for charged ones. This creates the possibility to create missions that are automatic and require no input from a pilot. Due to the dynamic nature of weather the flight speeds of the mission need to be changed. By changing the speeds safety and higher operational ability is achieved. Current technology does not dynamically change the mission parameters to fit the weather conditions. 

This thesis does not concern itself with use cases where high situational awareness is needed such as detecting objects in video, tracking objects in video, dynamically generating new missions given external stimulus. Instead use cases that use missions that follow a preplanned path are discussed. Such use cases are area surveillance missions for securing a perimeter of a secure site or autonomous patrol of a segment of a countries border.

More concretely in this thesis the library of binary flight logs of Eli Ltd is taken and used to build a database for further analysis. In the first chapter we survey the state of the art. The second chapter discusses the intricacies of piloting an unmanned aerial multirotor vehicle. In the third chapter various file formats are analyzed and chosen from to be used as storage for the database. Furthermore the analysis prerequisites are discussed and the database schema is designed accordingly. The schema is then used in the _python_ code created by the thesis author to translate the binary flight logs into a _SQLite_ database. In the following chapter initial analysis is conducted on the data. The goal of which is to find the relevant data to model the multirotor behavior in different conditions and requirements for the model to be used in practice.

